\input texinfo.tex

@afourpaper
@fonttextsize 11

@latex
\renewcommand{\topfraction}{.85}
\renewcommand{\bottomfraction}{.75}
\renewcommand{\textfraction}{.15}
\renewcommand{\floatpagefraction}{.85}
\geometry{margin=1.25in}

\overfullrule=1mm
\usepackage[width=.75\textwidth,indention=.5cm]{caption}
\usepackage{xcolor}
\usepackage{listings}

\definecolor{gray1}{gray}{0.75}
\definecolor{gray2}{gray}{0.4}
\definecolor{gray3}{gray}{0.25}

\lstset{
        showstringspaces=false,
        @c Frame
        framexleftmargin=1em,
        framexrightmargin=1em,
        framextopmargin=4pt,
        xleftmargin=1em,
        xrightmargin=1em,
        @c Style
        rulecolor=\color{gray1},
        basicstyle=\ttfamily\small\color{gray2},
        identifierstyle=\color{black}\bfseries,
        keywordstyle=\color{gray3},
        commentstyle=\slshape,
        @c Center tildes vertically
        literate={~}{{\raisebox{0.5ex}{\texttildelow}}}{1}
}

\lstdefinestyle{lua} {
        language={[5.3]Lua}
}

\lstdefinestyle{scheme} {
        language={Lisp}
}

\lstdefinestyle{init} {
        language={sh}
}

\lstdefinestyle{make} {
        language={[gnu]make}
}

@end latex

@copying
Copyright @copyright{} 2026 Dimitris Papavasiliou.

This manual is for version @value{gamma_version} of Gamma and version
@value{gammadb_version} of its Debgugger.  It is covered by the
@acronym{GNU} Free Documentation License.  @xref{@acronym{GNU} Free
Documentation License}.

Gamma is freely redistributable software. You may redistribute it
and/or modify it under the terms of the @acronym{GNU} General Public
License as published by the Free Software Foundation.
@xref{@acronym{GNU} General Public License}.
@end copying

@documentinfo
@title Gamma
@subtitle For Gamma version @value{gamma_version}, Debugger version @value{gammadb_version}
@subtitle @value{updated}
@author Dimitris Papavasiliou
@end documentinfo

@maketitle

@contents

@node Top
@top Gamma

This manual is for version @value{gamma_version} of Gamma and version
@value{gammadb_version} of its Debgugger, updated @value{updated}.

@include doc_manual_introduction.texi
@include doc_manual_getting_started.texi

@node @acronym{GNU} General Public License
@appendix @acronym{GNU} General Public License
@include gpl-3.0.texi

@node @acronym{GNU} Free Documentation License
@appendix @acronym{GNU} Free Documentation License
@include fdl-1.3.texi

@node Concept Index
@unnumbered Concept Index

@printindex cp
@bye
