\input texinfo.tex
@afourpaper
@fonttextsize 11

@latex
\overfullrule=1mm
@end latex

@contents

@include src_main_cpp.texi

@node @acronym{GNU} General Public License
@appendix @acronym{GNU} General Public License
@include gpl-3.0.texi

@node @acronym{GNU} Free Documentation License
@appendix @acronym{GNU} Free Documentation License
@include fdl-1.3.texi
