// Copyright 2022 Dimitris Papavasiliou

// This file is part of Gamma.

// Gamma is free software: you can redistribute it and/or modify it under the
// terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.

// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
// details.

// You should have received a copy of the GNU General Public License along with
// this program. If not, see <https://www.gnu.org/licenses/>.

#include <forward_list>

#include "kernel.h"
#include "macros.h"
#include "boxed_operations.h"
#include "evaluation.h"

// Document: program

// ## Program Messages

// Sometimes, it's useful for the program to be able to display its
// own messages during evaluation.  For consistency, we'd like these
// to resemble the other messages generated by the front or back end,
// i.e. to include source location information and level and have the
// same formatting.

void print_message(Operation::Message_level level, const char *s, const int n)
{
    // The easiest way to print the message is to create a dummy
    // operation type and co-opt its message printing mechanism.  Ref:
    // Operation Evaluation Messages.

    class: public Operation {
    public:
        std::string describe() const override {
            assert_not_reached();
        }

        void reset() override {
            assert_not_reached();
        }

        void evaluate() override {
            assert_not_reached();
        }
    } op;

    op.message(level, std::string(s, n));
}

// ## Outputs

// Some of the operations defined in a front end program, those that
// are considered the utimate results it is intended to create, are
// designated as *outputs*.  An output can be named, which is the
// usual case, but it can also be unnamed.  The latter is mostly of
// use when we want to temporarily turn a part of the overall
// computation into an output, in order to inspect it for debugging.

// There can be more than one output and all *can* be, but need not
// be, enabled in a given invocation.  What outputs are *enabled*,
// meaning that their respective operations will be evaluated in some
// form, is controlled by the user via several command line switches.

void insert_output_operations(
    std::string name, std::vector<Boxed_polyhedron> &v)
{
    // When the front end is asked to mark an operation as an output, it
    // checks whether the output is enabled and if so, creates one or more
    // output operations and "sinks" them (ref: Sunk Operations).

    // It can be more than one, because a give output may have been
    // requested in more than one formats by the user.  We gather all
    // output operations to be created into the following list.

    std::forward_list<std::pair <const std::string, int>> outputs;

    // Outputs can be enabled per-format, for example with the
    // `--output-stl` option.  In this case all named outputs are
    // enabled and an output with name `foo` will be written into the
    // file `foo.stl`.

    const std::string suffixes[] = {".stl", ".off", ".wrl"};
    const int flags[] = {
        Flags::output_stl, Flags::output_off, Flags::output_wrl};

    const int n = sizeof(suffixes) / sizeof(suffixes[0]);
    assert(n == sizeof(flags) / sizeof(flags[0]));

    const std::size_t m = name.size();

    if (m > 0) {
        for (int i = 0; i < n; i++) {
            if (flags[i]) {
                outputs.push_front({name + suffixes[i], i});
            }
        }
    }

    // Specific outputs can also be enabled eg. with the
    // `-o`/`--output=spec` options.  An output spec can be of the
    // form:

    for (const auto &x: Options::outputs) {
        if (std::size_t j = x.find_first_of(':');
            j != std::string::npos) {
            //   1. `foo.ext:bar`, in which case explicitly selected
            //   output named `bar` is written to the file `foo.ext`,
            //   with a format determined by the extension.  If the
            //   `foo.ext` part is omitted, the output is piped to the
            //   debugger.  If the `bar` part is omitted, the unnamed
            //   output is selected.

            if (x.compare(j + 1, std::string::npos, name)) {
                continue;
            }

            for (int i = 0; i < n; i++) {
                const std::size_t m = suffixes[i].size();

                if (j >= m && !x.compare(j - m, m, suffixes[i])) {
                    outputs.push_front({x.substr(0, j), i});
                    goto next_output;
                }
            }

            outputs.push_front({x.substr(0, j), -1});
        } else {
            //   2. `foo.ext`, in which case the output named `foo` is
            //   written to the file `foo.ext`, in the corresponding
            //   format.

            if (!m || x.compare(0, m, name)) {
                continue;
            }

            for (int i = 0; i < n; i++) {
                if (!x.compare(m, std::string::npos, suffixes[i])) {
                    outputs.push_front({x, i});
                    goto next_output;
                }
            }

            outputs.push_front({x, -1});
        }

      next_output:;
    }

    // If `outputs` is empty, this output wasn't enabled in this
    // invocation.

    if (outputs.empty()) {
        if (Flags::warn_outputs) {
            if (name.empty()) {
                const char *s = "unused null output";
                print_message(Operation::WARNING, s, std::strlen(s));
            } else {
                std::ostringstream s;
                s << "unused output '" << name << '\'';

                std::string t = s.str();
                print_message(Operation::WARNING, t.c_str(), t.size());
            }
        }

        // If the user has specifically disabled dead operation
        // elimination, we include this operation as a quasi-sink
        // operation, to prevent it and its predecessors from being
        // discarded.

        // Note that, while `sink_operation` will try to move the
        // provided `std::shared_ptr`, omitting `std::move`, will
        // prevent that and copy it instead.  This is deliberate, as
        // we don't want to destroy the boxed pointer, which
        // technically belongs to the front end.

        if (!Flags::eliminate_dead_operations) {
            for (auto &p: v) {
                std::visit(
                    [](auto &&x) {
                        sink_operation(x);
                        assert(x);
                    }, p);
            }
        }

        return;
    }

    // If some outputs have been enabled, we need to convert all
    // provided operations (in `v`) to a mesh, if they aren't already
    // meshes and create the required write operations.

    std::vector<std::shared_ptr<Polyhedron_operation<Surface_mesh>>> w;
    w.reserve(v.size());

    for (const auto &p: v) {
        w.push_back(
            std::visit(
                [](auto &&x) {
                    return CONVERT_TO<Surface_mesh,
                                      Polyhedron_operation<Surface_mesh>>(x);
                }, p));
    }

    for (const auto &[s, i]: outputs) {
        switch (i) {
            case -1:
            sink_operation(INSPECT(s.c_str(), std::vector(w)));
            break;

            case 0:
            sink_operation(WRITE_STL(s.c_str(), std::vector(w)));
            break;

            case 1:
            sink_operation(WRITE_OFF(s.c_str(), std::vector(w)));
            break;

            case 2:
            sink_operation(WRITE_WRL(s.c_str(), std::vector(w)));
            break;
        }
    }
}
